Lesson 8
taras-kobetiak/Angular-Mentoring-Programm pull request #10
Opened 2022-07-31 12:56 UTC by Zyupa

2022-08-13 13:49 UTC, artur-dorosh requested changes

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.html
> +                <app-calendar [creationDate]="dataToSendInCalendar" (creationDateChange)="creationDateChange($event)">
not well variable name)

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +      this.newCourse();
addNewCourse would be better name

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +  async updateCourse(): Promise<void> {
you don't need to do it async especially declare return type as Promise<void> when you don't return anything)
it should looks as something like this:
```
 updateCourse(): void {
    this.courseService.updateCourse(this.course).then(() => this.router.navigate(['/courses']));
  }
```

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +  async newCourse(): Promise<void> {
the same here, please rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    if (!this.courses.find(course => course.id === this.temporaryId + '')) {
this.temporaryId.toString() or `${this.temporaryId}` but definitely not this.temporaryId + ''

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +      this.generateId();
recursion just for incrementation, really?)

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +  async takeCourseData(): Promise<void> {
the same as updateCourse
and check all places where you used Promise<void> as return type and rewrite them

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    let courseData = await this.courseService.getCourseById(this.courseId);
I believe this variable is redundant

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    this.course.creationDate = new Date(this.course.creationDate);
really strange manipulations

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/calendar/calendar.component.ts
> +  ngDoCheck(): void {
terrible decision, check how many times this function calls just on "edit course" button click
![image](https://user-images.githubusercontent.com/50192515/184495919-4b38649c-2048-403a-8d5c-d5d7e239f37d.png)

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/add-course-page/calendar/calendar.component.ts
> +  ngDoCheck(): void {
11 times
if you want wait for data and set plug data follow next way within template
![image](https://user-images.githubusercontent.com/50192515/184496019-af8a362a-a60d-48f5-83dc-eb208462540b.png)

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/app.component.ts
> +    this.isAuth = this.authService.isAuthenticated();
the same here, really many calls
at least please add check
```
if (this.isAuth !== null) {
  this.isAuth = this.authService.isAuthenticated();
}
```

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/authentication/interceptor/auth.interceptor.ts
> +            let response = await this.authService.getUserInfo('taras@.com');
interceptor doesn't work with fetch but... wtf)
I just skip this file now due to future rewriting

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/authentication/services/auth-service.service.ts
> +    let userData = await fetch('http://localhost:3000/users');
you should know what specific endpoint returns
e.g. IUserEntyty[] or something else
also you don't need async/await here
```
logIn(): Promise<IUserEntyty[]> {
  return fetch('http://localhost:3000/users').then((data) => data.json());
}
```

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/authentication/services/auth-service.service.ts
> +  async getUserInfo(email: string): Promise<any> {
the same as logIn

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
> +      let courseData = await this.courseService.getCourseById(this.courseId);
redundant variable

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
> +  async setBreadcrumbs(): Promise<void> {
you don't need async/await here
please use "then" method of promises

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/header/header.component.html
> +            <p *ngIf="isAuth; else startScreen">Hello, {{currentUser.firstName}}</p>
don't forget use "?" to avoid errors

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/header/header.component.ts
> +    let userData: string | null = localStorage.getItem('currentUser');
why you don't do this using ngOnInit? DoCheck calling too often

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/login-page/login-page/login-page.component.ts
> +  async onSubmit(form: NgForm): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/login-page/login-page/login-page.component.ts
> +  async createUsersData(): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  async deleteComponent(id: string): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +    this.allCoursesLengthFunction();
try to refuse of this function

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  async loadNewCourses(): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  async findClick(inputData: string): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  async refreshCourse(): Promise<void> {
rewrite

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  async getCoursesList(courseLimit: number): Promise<any> {
rewrite as logIn

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  async getAllCoursesList(): Promise<any> {
and here

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  async getCourseById(id: string): Promise<any> {
and here

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  updateCourse(course: CoursePage): Promise<any> {
don't use any

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  async getCourseById(id: string): Promise<any> {
don't use any

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  deleteCourse(id: string): Promise<any> {
don't use any

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  addCourses(course: CoursePage): Promise<any> {
don't use any

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +  async getFilteredList(searchData: string): Promise<any> {
and here
don't use any

2022-08-13 13:49 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +      let findData = inputData.toLowerCase();
redundant variable

2022-08-14 11:47 UTC, taras-kobetiak commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    if (!this.courses.find(course => course.id === this.temporaryId + '')) {
тут, до речі, цікавинка. ${this.temporaryId} штука не робить, воно чогось не формує строку з того

2022-08-14 11:48 UTC, taras-kobetiak commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +      this.generateId();
а чим рекурсія погана? я так старався десь її втикнути. а що,якийсь дувайл цикл краще буде?

2022-08-16 17:26 UTC, artur-dorosh requested changes

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
>        ++this.temporaryId;
please use post incrementation

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/add-course-page/calendar/calendar.component.ts
> +  ngOnInit() {
you don't need this code block

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/authentication/interceptor/auth.interceptor.ts
>          console.log(userToken);
remove

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/authentication/services/auth-service.service.ts
> +    localStorage.removeItem('currentUser')
why you deleted semicolons?

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
>      if (this.breadcrumbsTitle) {
you can simplify it
remove if statement and use else block

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/login-page/login-page/login-page.component.ts
> +      let userInfo = this.authService.getUserInfo(this.currentUser.email)
why you need this variable?

2022-08-16 17:26 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  this.numberOfCourses += 3;
magic number antipattern
move value to constant

2022-08-16 20:12 UTC, artur-dorosh approved these changes

2022-08-16 20:12 UTC, merged