Second lesson
taras-kobetiak/Angular-Mentoring-Programm pull request #4
Opened 2022-06-12 12:37 UTC by Zyupa

2022-06-12 19:21 UTC, artur-dorosh commented
Merge conflict again. Please resolve

2022-06-12 19:58 UTC, artur-dorosh requested changes
resolve conflicts and check comments

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/add-course-button/add-course-button.component.scss
> +
delete unnecessary space

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/add-course-button/add-course-button.component.scss
> +
and here

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/add-course-button/add-course-button.component.ts
> +  }
add line break between methods please

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app-routing.module.ts
> +  { path: 'header', component: HeaderComponent },
do you really need route for header?

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.html
> +<app-nice-pop-up [hidden]="popIsHidden" (click1)="hiddenPop1()" (click3)="hiddenPop3()" (click4)="hiddenPop4()"
you don't need this popup
mentor insult will lead to negative consequences

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.scss
> +
line breaks

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.ts
> +  popIsHidden: boolean = true;
too many similar properties

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.ts
> +    console.log(1);
you should delete your debug flags on push

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.ts
> +    let a = confirm('Are you sure?')
variable is redundant

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.module.ts
> +    CoursesPageComponent,
as an option: you can create separate module for courses

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.scss
> +
spaces

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
> +  constructor() { }
just for aware - if you don't use constructor and other methods/hooks you can skip their declaration

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.html
> +                    <div class="timer">{{course.createHourAndMinutes()}}</div>
please use custom pipes instead class methods for data modification within template

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.html
> +            <div> <button class="edit" (click)="onEditClicked()">Edit</button></div>
extra space

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.scss
> +
line breaks again

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.ts
> +  @Input() course!: CoursePage;
you don't need "!" here
please never use it on inputs/outputs but better never use it)

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.ts
> +
line breaks
follow the same code stile within project

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/app.component.html
> +<!-- <router-outlet></router-outlet> -->
please delete this string

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/interfaces/classes.ts
> +import { IPage } from "./course.interface";
I believe you don't need this class and just interface is enough

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/interfaces/user-entyty.interface.ts
> +export interface IUserEntyty {
typo in interface name

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/interfaces/course.interface.ts
> +export interface IPage {
where you will use this interface?

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/interfaces/user-entyty.interface.ts
> +export interface IUserEntyty {
and what is a goal of this interface

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +  courses!: CoursePage[];
don't use "!"

2022-06-12 19:58 UTC, artur-dorosh commented on src/app/search-form/search-form.component.ts
> +  inputData!: string;
don't use "!" and please move all properties above constructor
not mandatory but good practice is follow this order: inputs -> outputs -> public properties -> protected properties  -> private properties -> constructor -> public methods -> protected methods -> private methods

2022-06-14 19:10 UTC, Zyupa commented on src/app/interfaces/classes.ts
> +import { IPage } from "./course.interface";
Поки удаляти не буду, бо влом + ще хотів би з геттерами і сеттерами розібратись. то як будеш дивитись, глянеш це місце. я там метод додав в pages-block\pages-block.component.ts. то він працює. а сеттер аналогічний чомусь ні

2022-06-14 19:11 UTC, taras-kobetiak commented on src/app/interfaces/user-entyty.interface.ts
> +export interface IUserEntyty {
це з тзшки. певно потім знадобиться для зберігання юзерів

2022-06-14 19:15 UTC, Zyupa commented on src/app/search-form/search-form.component.ts
> +  inputData!: string;
просто залишати без ! не виходить. можна зробити присвоїти рандомне значення, яке потім перепишеться. то зі строкою таке гарно виглядає. inputData: string = '' а от задавати якесь ліве число - то якось мабуть дивно буде?

2022-06-14 20:35 UTC, Zyupa commented on src/app/courses-page/courses-page.component.ts
> +  @Input() course!: CoursePage;
таки потребую. без знака оклику крашиться, хіба зробити = {і тут всі пусті властивості}

2022-06-15 20:18 UTC, artur-dorosh requested changes
Please fix configuration in tsconfig and a few comments

2022-06-15 20:18 UTC, artur-dorosh commented on src/app/courses-page/courses-page.component.ts
> +  @Input() course!: CoursePage;
"strictPropertyInitialization": false in tsconfig.json

2022-06-15 20:18 UTC, artur-dorosh commented on src/app/courses-page/date.pipe.ts
> +    transform(value: any, ...args: any[]): string {
you don't need "...args" here, please remove

2022-06-15 20:18 UTC, artur-dorosh commented on src/app/courses-page/date.pipe.ts
> +        return value.getHours() + 'h ' + value.getMinutes() + 'min'
please use ES6 syntax

2022-06-15 20:18 UTC, artur-dorosh commented on src/app/pages-block/pages-block.component.ts
> +    this.courses.splice(this.courses.findIndex(el => el.id === id), 1)
try avoid array mutation
e.g. here you can use Array.filter method

2022-06-15 20:18 UTC, artur-dorosh commented on src/app/search-form/search-form.component.ts
> +  inputData: string = '';
make line break between props and methods

2022-06-16 15:59 UTC, artur-dorosh approved these changes

2022-06-16 15:59 UTC, artur-dorosh commented on src/app/courses-page/date.pipe.ts
> +        return ` ${value.getHours()} h ${value.getMinutes()} min`
I believe you don't need space before hours)

2022-06-16 16:00 UTC, merged