Lesson 7
taras-kobetiak/Angular-Mentoring-Programm pull request #9
Opened 2022-07-02 09:14 UTC by Zyupa

2022-07-03 19:29 UTC, artur-dorosh requested changes

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    if (this.courseService.getCourseById(this.courseId)) {
you can cache method fire in const or move this.course data to const and write here
this.course = this.courseService.getCourseById(this.courseId) || defaultNewCourseData
try to avoid code duplication

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +      this.courseService.updateCourse(this.course)
don't forget semicolons
you're able to use ternary operator as well

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    durationInMinutes: 0,
I believe "durations" is enough for name)

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/app-routing.module.ts
> +  { path: 'login', component: LoginPageComponent },
if I'm not mistaken I had to create separate module for login
if you didn't create it so please do it now and use separate routing
please also use lazy loading for load this module

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/app-routing.module.ts
> +  { path: 'login', component: LoginPageComponent },
you can do the same for courses if you wish

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/app.component.ts
> +    if (this.authService.getUserInfo()) {
the same here, avoid code duplication

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/app-routing.module.ts
> +  { path: 'courses', component: PagesBlockComponent, canActivate: [isAuthGuard] },
I guess for guard better name will be just "authGuard"

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
> +  courseId: string | null;
you don't need declare null

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/breadcrumbs/breadcrumbs.component.ts
> +    if (idData.length === 3 && idData[2] != 'new') {
why length 3 and why you need third element?
it's not obvious for other developers
please try to use regExp here, it would great experience for you

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/guards/isAuth.guard.ts
> +        if (this.authService.getUserInfo()) {
avoid code duplication

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/header.component.html
> +            <p *ngIf="isAuth ||   temporaryStartScreen; else login" routerLink="login" (click)="onLogOutClick()">Log out
extra spaces

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/header.component.ts
>    temporaryStartScreen: boolean = true;
I suppose  you already don't need this variable

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/header.component.ts
> +  currentUserHello: string | undefined;
you can skip this string and write "Hello" in template

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/services/auth-service.service.ts
> +    localStorage.setItem(userInfo.email, userInfo.password);
you can store all user data in one storage item using JSON.stringify

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/services/auth-service.service.ts
> +    localStorage.setItem(userInfo.email, userInfo.password);
and for logout clear whole storage is bad idea, please remove specific item

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/header/services/auth-service.service.ts
> +    if (this.currentUser) {
you can simplify this if-else statement
return this.currentUser?.email
but I guess better return whole user info instead email only

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/login-page/login-page/login-page.component.html
> +                    <a routerLink="/courses">Forget password?</a>
do you really redirect user which forgot his password to courses?)))

2022-07-03 19:29 UTC, artur-dorosh commented on src/app/pages-block/services/courses.service.ts
> +    return this.course = this.courses.filter(course => course.id === id)[0]
use "find" here to return element instead array

2022-07-05 18:22 UTC, Zyupa commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    durationInMinutes: 0,
я теж так думав, але ТЗ було невблаганне)) ну, але в принципі, шо нам таке тз, як можна зробити краще)))

2022-07-09 14:37 UTC, Zyupa commented on src/app/app-routing.module.ts
> +  { path: 'login', component: LoginPageComponent },
коротше, тут я зробив, а на адд-курс чогось не вийшло, наче те саме роблю, а воно помилка [module build failed (Maximum+call+stack

2022-07-20 07:02 UTC, artur-dorosh requested changes

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    this.course = Object.assign({}, this.courseService.getCourseById(this.courseId)) || this.defaultCourseData;
please use {...oldValue, newValue} syntax

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +  creationDateChange(creationDate: Date) {
missed return value typedef

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/add-course-page/add-course-page/add-course-page.component.ts
> +    this.course.id = Math.floor(Math.random() * 100000000) + ''
it's not guarantee you never got the same id)

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/add-course-page/calendar/calendar.component.ts
> +      +this.creationDate - +new Date() > -100 && +this.creationDate - +new Date() < 0 ? this.placeholderData = 'Choose a date' :
please change "+" to Number()

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/add-course-page/calendar/calendar.component.ts
> +  onCreationDateChange(date: Date) {
missed return typedef

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/app-routing.module.ts
> +  // , canActivate: [AuthGuard]
remove please

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/app.component.ts
> +      this.currentUser = this.authService.getUserInfo().email;
would be better cache this data "this.authService.getUserInfo()" into separate variable and use it instead regular service method call

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/guards/isAuth.guard.ts
> +        this.currentUser = this.authService.getUserInfo().email || 'invalid'
I believe "invalid" value is redundant
you will get undefined if data don't exist

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/header/header.component.ts
> +    this.currentUser = this.authService.getUserInfo().email || 'noData'
the same
you don't need "noData"

2022-07-20 07:02 UTC, artur-dorosh commented on src/app/pages-block/pipes/order-by.pipe.ts
> +  pure: false
never use impure pipes, it slow down your app

2022-07-22 19:31 UTC, artur-dorosh approved these changes

2022-07-22 19:31 UTC, merged